services:
  # Backend API Service
  - type: web
    name: graphene-backend
    env: node
    region: oregon
    buildCommand: cd apps/backend && npm install
    startCommand: cd apps/backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://graphene-frontend.onrender.com
      - key: SUPPORT_EMAIL
        value: support@graphene-security.com
      - key: FROM_EMAIL
        value: noreply@graphene-security.com
      - key: FROM_NAME
        value: Graphene Security
      - key: EMAIL_SERVICE
        value: ses
      - key: AWS_REGION
        value: us-east-1
      - key: AWS_ACCESS_KEY_ID
        value: your-aws-access-key
      - key: AWS_SECRET_ACCESS_KEY
        value: your-aws-secret-key
      # PayPal Configuration
      - key: PAYPAL_CLIENT_ID
        value: your-paypal-client-id
      - key: PAYPAL_CLIENT_SECRET
        value: your-paypal-client-secret
      - key: PAYPAL_MODE
        value: live
      - key: PAYPAL_WEBHOOK_ID
        value: your-paypal-webhook-id
      # Blockonomics Configuration
      - key: BLOCKONOMICS_API_KEY
        value: your-blockonomics-api-key
      - key: BLOCKONOMICS_WEBHOOK_SECRET
        value: your-blockonomics-webhook-secret
      - key: BLOCKONOMICS_XPUB
        value: your-bitcoin-extended-public-key
      # NowPayments Configuration
      - key: NOWPAYMENTS_API_KEY
        value: your-nowpayments-api-key
      - key: NOWPAYMENTS_IPN_SECRET
        value: your-nowpayments-ipn-secret
      - key: NOWPAYMENTS_EMAIL
        value: your-nowpayments-account-email
    
  # Frontend Static Site
  - type: web
    name: graphene-frontend  
    env: static
    buildCommand: cd apps/frontend && npm install && rm -rf dist && npm run build
    staticPublishPath: apps/frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://graphene-backend.onrender.com/api
      - key: VITE_APP_TITLE
        value: Graphene Security
      - key: VITE_COMPANY_NAME
        value: Graphene Security
      - key: VITE_ENABLE_BITCOIN_PAYMENTS
        value: "true"
      - key: VITE_ENABLE_MONERO_PAYMENTS
        value: "true"
      - key: VITE_ENABLE_PAYPAL_PAYMENTS
        value: "true"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html