services:
  # Backend API Service
  - type: web
    name: graphene-backend
    env: node
    region: oregon
    buildCommand: cd apps/backend && npm install
    startCommand: cd apps/backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://graphene-frontend.onrender.com
      - key: SUPPORT_EMAIL
        value: support@graphene-security.com
      - key: FROM_EMAIL
        value: noreply@graphene-security.com
      - key: FROM_NAME
        value: GrapheneOS Store
      - key: EMAIL_SERVICE
        value: ses
      - key: AWS_REGION
        value: us-east-1
      - key: AWS_ACCESS_KEY_ID
        value: your-aws-access-key
      - key: AWS_SECRET_ACCESS_KEY
        value: your-aws-secret-key
    
  # Frontend Static Site
  - type: web
    name: graphene-frontend  
    env: static
    buildCommand: cd apps/frontend && npm install && rm -rf dist && npm run build
    staticPublishPath: apps/frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://graphene-backend.onrender.com/api
      - key: VITE_APP_TITLE
        value: GrapheneOS Store
      - key: VITE_COMPANY_NAME
        value: GrapheneOS Store
      - key: VITE_ENABLE_BITCOIN_PAYMENTS
        value: "true"
      - key: VITE_ENABLE_MONERO_PAYMENTS
        value: "true"
      - key: VITE_ENABLE_PAYPAL_PAYMENTS
        value: "true"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html